### ISSUE TITLE
BL Logic which releases SpawnHero Captives - Fix discussion

### ISSUE THREAD

**Issue by SkipWestcott** [BannerlordCE/CEEvents#80]
**Describe the bug**
Captive Wanderers released on generic Peace events.

**To Reproduce**
1. Spawn a wanderer prisoner
2. Peace with any faction
3. Wanderer is released

**Expected behavior**
Captive wanderers should not be at peace with Main Hero!!!

**Additional context**
>Hero hero = HeroCreator.CreateSpecialHero(wanderer, randomElementWithPredicate, **_CampaignData.NeutralFaction_**, CampaignData.NeutralFaction, -1);

This is the problem. This needs to pull in the Intended Clan. Let me see what I can find as far as correct syntax.

EDIT:
>Hero hero = HeroCreator.CreateSpecialHero(wanderer, randomElement, Clan.BanditFactions.GetRandomElementInefficiently(), null, -1);

You actually have this fixed in Master? Development reflects the first, erroneous pattern.

**Comment by SkipWestcott** [comment]
Submitted PR 85 to fix.

Technically, it could search the Faction space instead of just the BanditFaction space, and we could spawn merc clan concubines etc. But this is fine for now

**Comment by TheBadListener** [comment]
Closing issues as it has been merged :)
